#!/usr/bin/env bash
java -classpath \
 $(echo ~/esavo-reg-II/common/dist/*.jar                                                  | tr ' ' ':')\
:$(echo ~/esavo-reg-II/db-business-api/dist/*.jar                                         | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/database-diffable-dumper/lib-runtime/*.jar      | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/database-diffable-dumper/lib-ivy-compile/*.jar  | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/database-diffable-dumper/lib-ivy-runtime/*.jar  | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/database-diffable-dumper/dist/*.jar             | tr ' ' ':')\
 _int.esa.esavo.consoleutils.diffable_dumper.DBDiffableDumper $@

