#!/usr/bin/env bash
java -classpath $(echo ~/esavo-reg-II/ivoa-console-utils/esavo-swiss-knife/lib-ivy/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/common/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/esavo-swiss-knife/lib-runtime/*.jar | tr ' ' ':')\
:$(echo ~)/esavo-reg-II/ivoa-lib/dist/ivoalib.jar\
:$(echo ~/esavo-reg-II/db-business-api/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/valgraph/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/jfreechart-wrapper/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/curation/lib/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/registry-util/lib/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/harvester-lib/lib/dist/*.jar)\
:$(echo ~/esavo-reg-II/oai-pmh-lib/dist/*.jar)\
:$(echo ~/esavo-reg-II/ivoa-console-utils/registry-anomalies-report/dist/*.jar | tr ' ' ':')\
:$(echo ~)/esavo-reg-II/ivoa-console-utils/esavo-swiss-knife/dist/esavo-swiss-knife.jar\
   _int.esa.esavo.consoleutils.esaknife.EsavoSwissKnife $@




