#!/bin/bash
if [ $# -ne 2 ]
then
    echo "usage is $0 <top-of-folder-hierarchy> <grep pattern to look for in 'jar tvf' output>"
else
    FOLDER=$1
    THING_TO_LOOKFOR=$2
    find $FOLDER -iname \*.jar | while read f ; do echo $f && (jar tvf $f | grep -i $THING_TO_LOOKFOR) ; done
fi

