#!/usr/bin/env bash
if [[ ($# -ne 1) && ($# -ne 2) ]]
then
    echo "usage is $0 <grep pattern to look for in *.java files> [<top-of-folder-hierarchy> or, if missing, current dir]"
else
    THING_TO_LOOKFOR=$1
    FOLDER=${2:-.}

    find -L "$FOLDER" -iname \*.java -exec grep -i "$THING_TO_LOOKFOR" /dev/null {} \;
fi

