#!/bin/bash

# http://unix.stackexchange.com/a/308899/24044

if [ $# -gt 0 ]
then
    echo "usage is $0"
else
    DIRECTORY=$1
    for f in $(find . -type l ); do echo -n $(realpath $f) && echo -n "|" && echo $f ; done | grep -v "^$(pwd)" | cut -d \| -f 2
fi

