#!/bin/bash
if [ $# -ne 3 ]
then
    echo "usage is $0 <top-of-folder-hierarchy> <file extension> <grep pattern to look for in files of given file extension>"
else
    FOLDER=$1
    EXTENSION=$2
    THING_TO_LOOKFOR=$3
    find $FOLDER -iname \*.$EXTENSION -exec grep -i $THING_TO_LOOKFOR /dev/null {} \;
fi

