#!/usr/bin/env bash
if [[ ($# -ne 1) && ($# -ne 2) ]]
then
    echo "usage is $0 <grep pattern to look for in ASCII files> [<top-of-folder-hierarchy> or, if missing, current dir]"
else
    THING_TO_LOOK_FOR=$1
    FOLDER=${2:-.}
#    find -L "$FOLDER" -type f -exec grep -i "$THING_TO_LOOK_FOR" {} \; -exec file {} \; | grep text | cut -d ':' -f1
    (for f in $(find -L "$FOLDER" -type f); do grep -i "$THING_TO_LOOK_FOR" $f /dev/null; done)  | stripcolorcodes  | grep -i "$THING_TO_LOOK_FOR"
fi
