#!/bin/bash
if [ $# -ne 2 ]
then
    echo "usage is $0 <top-of-folder-hierarchy> <grep pattern to look for in *.xml files>"
else
    FOLDER=$1
    THING_TO_LOOKFOR=$2
    find $FOLDER -iname \*.xml -exec grep -i $THING_TO_LOOKFOR /dev/null {} \;
fi

