#!/usr/bin/env bash
java -classpath \
:$(echo ~/esavo-reg-II/common/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/xml-validation/lib/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-lib/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/ivoaval2/lib-ivy/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/ivoaval2/dist/*.jar    | tr ' ' ':')\
 _int.esa.esavo.consoleutils.ivoaval2.IVOAVAL2 $@

