#!/usr/bin/env bash
java -classpath \
:$(echo ~/esavo-reg-II/common/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-lib/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/harvester-lib/lib/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/oai-pmh-lib/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/registry-2way-comparison-report/lib-ivy/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/registry-2way-comparison-report/dist/*.jar | tr ' ' ':')\
 _int.esa.esavo.consoleutils.registry2waycomparison.Registry2WComparisonReport $@

