#!/usr/bin/env bash
java -classpath \
 $(echo ~/esavo-reg-II/curation/lib/lib-ivy/*.jar               | tr ' ' ':')\
:$(echo ~/esavo-reg-II/common/dist/*.jar                         | tr ' ' ':')\
:$(echo ~/esavo-reg-II/curation/lib/dist/*.jar                  | tr ' ' ':')\
:$(echo ~/esavo-reg-II/xml-validation/lib/dist/*.jar             | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/sval/lib-ivy/*.jar    | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/sval/dist/*.jar       | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/sval/lib-runtime/*.jar| tr ' ' ':')\
:$(echo ~/esavo-reg-II/harvester-lib/lib/lib-ivy/*.jar           | tr ' ' ':')\
:$(echo ~/esavo-reg-II/harvester-lib/lib/dist/*.jar              | tr ' ' ':')\
 _int.esa.esavo.consoleutils.sval.SVAL $@
