#!/usr/bin/env bash
java -classpath \
 $(echo ~/esavo-reg-II/ivoa-lib/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/xml-validation/lib/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/vols/lib-ivy/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/vols/lib-runtime/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/vols/dist/vols.jar)\
:$(echo ~/esavo-reg-II/common/dist/*.jar | tr ' ' ':')\
 _int.esa.esavo.consoleutils.vols.VOLS $@