#!/usr/bin/env bash
CLASSPATH=$(echo ~/esavo-reg-II/common/dist/esavo-common.jar):$(echo ~/esavo-reg-II/common/lib-ivy/*.jar | tr ' ' ':'):$(echo ~/esavo-reg-II/xml-lib/lib-ivy/*.jar | tr ' ' ':'):$(echo ~/esavo-reg-II/xml-lib/dist/xmlutil.jar):$(echo ~/esavo-reg-II/harvester-lib/02/lib/lib-ivy/*.jar | tr ' ' ':'):$(echo ~/esavo-reg-II/ivoa-consol-utils/voshell/lib-compile/*.jar | tr ' ' ':'):$(echo ~/esavo-reg-II/ivoa-console-utils/voshell/lib-ivy/*.jar | tr ' ' ':'):$(echo ~/esavo-reg-II/ivoa-console-utils/voshell/lib-compile/*.jar | tr ' ' ':'):$(echo ~/esavo-reg-II/ivoa-console-utils/voshell/dist/foo.jar)
echo "using CLASSPATH=$CLASSPATH"
java -cp "$CLASSPATH" _int.esa.esavo.consoleutils.voshell.VOShell
