#!/usr/bin/env bash
java -classpath \
:$(echo ~/esavo-reg-II/common/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/xml-validation/lib/dist/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/xsdval2/lib-ivy/*.jar | tr ' ' ':')\
:$(echo ~/esavo-reg-II/ivoa-console-utils/xsdval2/dist/*.jar    | tr ' ' ':')\
 _int.esa.esavo.consoleutils.xsdval2.XSDVAL2 $@

